version: '2'
services:
  datastore:
    image: mysql
    expose:
      - "3306"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd1234
    volumes:
      - ./datastore:/docker-entrypoint-initdb.d

volumes:
  datastore: